MvcKutuphane/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
	public class DuyuruController : Controller
	{
		// GET: Duyuru
		DBKUTUPHANEEntities2 db = new DBKUTUPHANEEntities2();
		public ActionResult Index()
		{
			var degerler = db.TBLDUYURULAR.ToList();
			return View(degerler);
		}

		[HttpGet]
		public ActionResult YeniDuyuru()
		{ 
			return View(); 
		}

		[HttpPost]
		public ActionResult YeniDuyuru(TBLDUYURULAR t)
		{
			db.TBLDUYURULAR.Add(t);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult DuyuruSil(int id)
		{
			var duyuru = db.TBLDUYURULAR.Find(id);
			db.TBLDUYURULAR.Remove(duyuru);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult DuyuruDetay(TBLDUYURULAR p)
		{
			var duyuru = db.TBLDUYURULAR.Find(p.ID);
			return View("DuyuruDetay",duyuru); 
		}
		public ActionResult DuyuruGuncelle(TBLDUYURULAR t)
		{
			var duyuru = db.TBLDUYURULAR.Find(t.ID);
			duyuru.KATEGORİ = t.KATEGORİ;
			duyuru.ICERIK = t.ICERIK;
			duyuru.TARIH = t.TARIH;
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURULAR
@{
   ViewBag.Title = "DuyuruDetay";
   Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
   <div style="margin-bottom:15px;"></div>
   <div class="form-group">
      @Html.LabelFor(k => k.ID)
      @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
      <br />

      <label>DUYURU KATEGORİ</label>
      @Html.TextBoxFor(k => k.KATEGORİ, new { @class = "form-control" })
      <br />
      <label>DUYURU IÇERİK</label>
      @Html.TextAreaFor(k => k.ICERIK, new { @class = "form-control" })
      <br />
      <label>DUYURU TARİH</label>
      @Html.TextBoxFor(k => k.TARIH, new { @class = "form-control" })
   </div>
   <div>
      <button class="btn btn-warning">Güncelle</button>
   </div>
}

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity;
@model List<TBLDUYURULAR>
@{
   ViewBag.Title = "Index";
   Layout = "~/Views/Shared/Layout.cshtml";
   string renk = "";
}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<h2>Duyurular</h2>

<table class="table table-bordered">
   <tr>
      <th>DUYURU ID</th>
      <th>KATEGORİ ADI</th>
      <th>TARİH</th>
      <th>SİL</th>
      <th>İÇERİK</th>

   </tr>

   @foreach (var d in Model)
   {
      if (d.KATEGORİ == "Diğer")
      {
         renk = "bg-info text-white";
      }

      if (d.KATEGORİ == "Yeni Kitap")
      {
         renk = "bg-warning text-white";
      }
      if (d.KATEGORİ == "İletişim")
      {
         renk = "bg-danger text-white";
      }
      if (d.KATEGORİ == "Kitapları Geçiktirmeyin")
      {
         renk = "bg-primary text-white";
      }

      <tr class="@renk">
         <td>@d.ID</td>
         <td >@d.KATEGORİ</td>
         <td>@Convert.ToDateTime(d.TARIH).ToString("dd/MM/yyyy")</td>
         <td><a href="/Duyuru/DuyuruSil/@d.ID" class="btn btn-danger" style="width:60px;">Sil</a></td>
         <td><a href="/Duyuru/DuyuruDetay/@d.ID" class="btn btn-default" style="background-color:darksalmon;">Detaylar</a></td>
      </tr>
   }
</table>
<a href="/Duyuru/YeniDuyuru/" class="btn btn-primary">Yeni Duyuru Ekle</a>

MvcKutuphane/Views/Duyuru/YeniDuyuru.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURULAR
@{
   ViewBag.Title = "YeniDuyuru";
   Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
   <div></div>
   <div style="margin-top:15px;">
      <label>Duyuru Kategorisi</label>
      @Html.TextBoxFor(x => x.KATEGORİ, new { @class = "form-control" })
   </div>
   <div style="margin-top:15px;">
      <label>Duyuru İçerik</label>
      @Html.TextBoxFor(x => x.ICERIK, new { @class = "form-control" })
   </div>
   <div style="margin-top:15px;">
      <label>Duyuru Taih</label>
      @Html.TextBoxFor(x => x.TARIH, new { @class = "form-control" })
   </div>
   <div style="margin-top:15px;">
      <button class="btn btn-info" id="Btn1">Duyuru Ekle</button>
   </div>
</form>