MvcKutuphane/Controllers/VitrinController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Siniflarim;
namespace MvcKutuphane.Controllers
{
   [AllowAnonymous]
   public class VitrinController : Controller
	{
		// GET: Vitrin
		DBKUTUPHANEEntities2 db = new DBKUTUPHANEEntities2();
		[HttpGet]
		public ActionResult Index()
		{
			Class1 cs = new Class1();
			cs.Deger1 = db.TBLKITAP.ToList();
			cs.Deger2 = db.TBLHAKKIMIZDA.ToList();
			//var degerler = db.TBLKITAP.ToList();
			return View(cs);
		}

		[HttpPost]
		public ActionResult Index(TBLILETISIM t) 
		{ 
			db.TBLILETISIM.Add(t);
			db.SaveChanges();
			return RedirectToAction("Index");
		}




	}
}

MvcKutuphane/Views/Vitrin/Index.cshtml
@model MvcKutuphane.Models.Siniflarim.Class1
@{
   Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <meta name="description" content="">
   <meta name="author" content="">

   <title>Freelancer - Start Bootstrap Theme</title>

   <!-- Custom fonts for this theme -->
   <link href="~/web/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
   <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
   <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

   <!-- Theme CSS -->
   <link href="~/web/css/freelancer.min.css" rel="stylesheet">

</head>

<body id="page-top">

   <!-- Navigation -->
   <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
      <div class="container">
         <a class="navbar-brand js-scroll-trigger" href="#page-top">DİJİTAL KÜTÜPHANEM</a>
         <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
         </button>
         <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
               <li class="nav-item mx-0 mx-lg-1">
                  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Kitaplarımız</a>
               </li>
               <li class="nav-item mx-0 mx-lg-1">
                  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Hakkımızda</a>
               </li>
               <li class="nav-item mx-0 mx-lg-1">
                  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">İletişim</a>
               </li>
               <li class="nav-item mx-0 mx-lg-1">
                  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/Login/GirisYap/">Login</a>
               </li>
            </ul>
         </div>
      </div>
   </nav>

   <!-- Masthead -->
   <header class="masthead bg-success text-white text-center">
      <div class="container d-flex align-items-center flex-column">

         <!-- Masthead Avatar Image -->
         <img class="masthead-avatar mb-5" src="~/web/img/library.png" alt="">

         <!-- Masthead Heading -->
         <h1 class="masthead-heading text-uppercase mb-0">KÜTÜPHANEMİZE HOŞGELDİNİZ</h1>

         <!-- Icon Divider -->
         <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
               <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
         </div>

         <!-- Masthead Subheading -->
         <p class="masthead-subheading font-weight-light mb-0">
            "Kitap Dolu Bahçe , Çiçek Dolu Bir Ev <br />
            İnsanların aynası kitaplardır , İyi bir kitap bir hazinedir."

         </p>

      </div>
   </header>
 
   <!-- Portfolio Section -->

   <section class="page-section" id="portfolio" style="background-color:
   #387681;">
      <div class="container">
         <!-- Portfolio Section Heading -->
         <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">KİTAPLARIMIZ</h2>

         <!-- Icon Divider -->
         <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
               <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
         </div>

         <!-- Portfolio Grid Items -->
         <div class="row">

            @foreach (var x in Model.Deger1)
            {


               <!-- Portfolio Item 1 -->
               <div class="col-md-6 col-lg-3">
                  <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
                     <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white">

                        </div>
                     </div>
                     <img class="img-fluid" src="@x.KITAPRESIM" style="width:250px; height:350px; margin-top:15px;" alt="">
                  </div>
               </div>
            }
         </div>
         <!-- /.row -->

      </div>
   </section>

   <br />
   <!-- About Section -->
   <section class="page-section bg-info text-white  mb-0" id="about" style="margin-top:-25px;">
      <div class="container">

         <!-- About Section Heading -->
         <h2 class="page-section-heading text-center text-uppercase text-white ">HAKKIMIZDA</h2>

         <!-- Icon Divider -->
         <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
               <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
         </div>

         <!-- About Section Content -->
         <div class="row">

            @foreach (var x in Model.Deger2)
            {
               @x.ACIKLAMA
            }


         </div>




      </div>
   </section>

   <!-- Contact Section -->
   <section class="page-section" id="contact" style="background-color:burlywood;">
      <div class="container">

         <!-- Contact Section Heading -->
         <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">İLETİŞİM</h2>

         <!-- Icon Divider -->
         <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
               <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
         </div>

         <!-- Contact Section Form -->
         <div class="row">
            <div class="col-lg-8 mx-auto">
               <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
               @using (Html.BeginForm("Index", "Vitrin", FormMethod.Post))
               {
                  <form name="sentMessage" id="contactForm" novalidate="novalidate">
                     <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                           <label>Ad Soyad</label>
                           <input class="form-control" id="name" name="AD" type="text" placeholder="Adınız Soyadınız" required="required" data-validation-required-message="Please enter your name.">
                           <p class="help-block text-danger"></p>
                        </div>
                     </div>
                     <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                           <label>Email Adresi</label>
                           <input class="form-control" name="MAIL" id="email" type="email" placeholder="Mail Adresiniz" required="required" data-validation-required-message="Please enter your email address.">
                           <p class="help-block text-danger"></p>
                        </div>
                     </div>
                     <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                           <label>Mesaj Konsu</label>
                           <input class="form-control" name="KONU" id="phone" type="tel" placeholder="Mesaj Konusu" required="required" data-validation-required-message="Please enter your phone number.">
                           <p class="help-block text-danger"></p>
                        </div>
                     </div>
                     <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                           <label>Mesajınız</label>
                           <textarea class="form-control" name="MESAJ" id="message" rows="5" placeholder="Mesajınız" required="required" data-validation-required-message="Please enter a message."></textarea>
                           <p class="help-block text-danger"></p>
                        </div>
                     </div>
                     <br>
                     <div id="success"></div>
                     <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Gönder</button>
                     </div>
                  </form>
               }
            </div>
         </div>

      </div>
   </section>

   <!-- Footer -->
   <footer class="footer text-center">
      <div class="container">
         <div class="row">

            <!-- Footer Location -->
            <div class="col-lg-4 mb-5 mb-lg-0">
               <h4 class="text-uppercase mb-4">Adresimiz</h4>
               <p class="lead mb-0">
                  34000 İstanbul Ümraniye
                  <br>Türkiye
               </p>
            </div>

            <!-- Footer Social Icons -->
            <div class="col-lg-4 mb-5 mb-lg-0">
               <h4 class="text-uppercase mb-4">Sosyal Medya Hesaplarımız</h4>
               <a class="btn btn-outline-light btn-social mx-1" href="#">
                  <i class="fab fa-fw fa-facebook-f"></i>
               </a>
               <a class="btn btn-outline-light btn-social mx-1" href="#">
                  <i class="fab fa-fw fa-twitter"></i>
               </a>
               <a class="btn btn-outline-light btn-social mx-1" href="#">
                  <i class="fab fa-fw fa-linkedin-in"></i>
               </a>
               <a class="btn btn-outline-light btn-social mx-1" href="#">
                  <i class="fab fa-fw fa-dribbble"></i>
               </a>
            </div>

            <!-- Footer About Text -->
            <div class="col-lg-4">
               <h4 class="text-uppercase mb-4">Kutuphane Mödülü</h4>
               <p class="lead mb-0">
                  Bu Proje Mv5 platformunda bootsrap.js.css tasarımları ile hazırlandı
                  <a href="http://startbootstrap.com">Start Bootstrap</a>.
               </p>
            </div>

         </div>
      </div>
   </footer>

   <!-- Copyright Section -->
   <section class="copyright py-4 text-center text-white">
      <div class="container">
         <small>Copyright &copy; Your Website 2024</small>
      </div>
   </section>

   <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
   <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
         <i class="fa fa-chevron-up"></i>
      </a>
   </div>







   <!-- Bootstrap core JavaScript -->
   <script src="~/web/vendor/jquery/jquery.min.js"></script>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

   <!-- Plugin JavaScript -->
   <script src="~/web/vendor/jquery-easing/jquery.easing.min.js"></script>

   <!-- Contact Form JavaScript -->
   <script src="~/web/js/jqBootstrapValidation.js"></script>
   <script src="~/web/js/contact_me.js"></script>

   <!-- Custom scripts for this template -->
   <script src="~/web/js/freelancer.min.js"></script>

</body>

</html>