MvcKutuphane/Controllers/AyarlarController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
   public class AyarlarController : Controller
   {
      // GET: Ayarlar
      DBKUTUPHANEEntities2 db = new DBKUTUPHANEEntities2();
  
      public ActionResult Index()
      {
         var kullanicilar = db.TBLADMIN.ToList();
         return View(kullanicilar);
      }
      [HttpGet]
      public ActionResult YeniAdmin()
      {
         return View();
      }

      [HttpPost]
      public ActionResult YeniAdmin(TBLADMIN t)
      {
         db.TBLADMIN.Add(t);
         db.SaveChanges();
         return RedirectToAction("Index");
      }
      public ActionResult AdminSil(int id)
      {
			var admin = db.TBLADMIN.Find(id);
			db.TBLADMIN.Remove(admin);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

      [HttpGet]
      public ActionResult AdminGuncelle(int id)
      {
			var admin = db.TBLADMIN.Find(id);
			return View("AdminGuncelle", admin);
		}

		[HttpPost]
		public ActionResult AdminGuncelle(TBLADMIN p)
		{
			var admin = db.TBLADMIN.Find(p.ID);
			admin.Kullanici = p.Kullanici;
			admin.Sifre = p.Sifre;
			admin.Yetki = p.Yetki;
			db.SaveChanges();
			return RedirectToAction("Index");
		}


	}
}

MvcKutuphane/Views/Ayarlar/AdminGuncelle.cshtml
@model MvcKutuphane.Models.Entity.TBLADMIN
@{
   ViewBag.Title = "AdminGuncelle";
   Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("AdminGuncelle", "Ayarlar", FormMethod.Post))
{
   <div style="margin-bottom:15px;"></div>
   <div class="form-group">
      @Html.LabelFor(k => k.ID)
      @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
      <br />
      @*@Html.LabelFor(k => k.AD)*@
      <label>Kullanıcı Adı</label>
      @Html.TextBoxFor(k => k.Kullanici, new { @class = "form-control" })
      <br />
      @*@Html.LabelFor(k => k.AD)*@
      <label>Sifre</label>
      @Html.TextBoxFor(k => k.Sifre, new { @class = "form-control" })
      <br />
      @*@Html.LabelFor(k => k.AD)*@
      <label>Yetki</label>
      @Html.TextBoxFor(k => k.Yetki, new { @class = "form-control" })
   </div>
   <div>
      <button class="btn btn-warning">Güncelle</button>
   </div>
}

MvcKutuphane/Views/Ayarlar/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLADMIN>
@{
   ViewBag.Title = "Index";
   Layout = "~/Views/Shared/Layout.cshtml";
}



<!-- Bootstrap JS and dependencies (jQuery and Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<!-- Popper.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<br />
<table class="table table-bordered">
   <tr>
      <th>ID</th>
      <th>Kullanıcı</th>
      <th>Yetki</th>
      <th>Sil</th>
      <th>Düzenle</th>
   </tr>
   @foreach (var item in Model)
   {
      <tr>
         <td>@item.ID</td>
         <td>@item.Kullanici</td>
         <td>@item.Yetki</td>
         <td class="project-actions">
            <a class="btn btn-info btn-sm" href="/Ayarlar/AdminGuncelle/@item.ID">
               <i class="fas fa-pencil-alt"></i>
               DUZENLE
            </a>
         </td>
         <td>
            <a class="btn btn-danger btn-sm" href="/Ayarlar/AdminSil/@item.ID">
               <i class="fas fa-trash"></i>
               Sil
            </a>
         </td>
      </tr>
   }
</table>
<br />

<!-- Yeni Admin Ekle Butonu -->
<a class="btn btn-primary" href="#" data-toggle="modal" data-target="#Modal1">Yeni Admin Ekle</a>



<div class="modal" id="Modal1" style="background-color:white;">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h2 class="modal-title">Admin Ekleme Paneli</h2>
         </div>
         <form method="post" action="/Ayarlar/YeniAdmin/">
            <div class="modal-body">
               <label>Kullanıcı Adı</label>
               <input type="text" name="Kullanici" class="form-control" />
               <br />
               <label>Şifre</label>
               <input type="text" name="Sifre" class="form-control" />
               <br />
               <label>Yetki </label>
               <input type="text" name="Yetki" class="form-control" />
               <br />
               <button class="btn btn-warning">Kaydet</button>
            </div>

         </form>
      </div>
   </div>
</div>